export enum ErrorType {
    AUTH_ERROR = "AUTH_ERROR",
    DB_ERROR = "DB_ERROR",
    VALIDATION_ERROR = "VALIDATION_ERROR",
    NOT_FOUND_ERROR = "NOT_FOUND_ERROR",
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
    BAD_REQUEST_ERROR = "BAD_REQUEST_ERROR",
    CONFLICT_ERROR = "CONFLICT_ERROR",
    INVALID_TOKEN_ERROR = "INVALID_TOKEN_ERROR",
    EXPIRED_TOKEN_ERROR = "EXPIRED_TOKEN_ERROR",
    UNAUTHORIZED_ERROR = "UNAUTHORIZED_ERROR",
    AWS_ERROR = "AWS_ERROR",
}

export const ErrorTypeCode: Record<ErrorType, number> = {
    [ErrorType.AUTH_ERROR]: 401,
    [ErrorType.DB_ERROR]: 500,
    [ErrorType.VALIDATION_ERROR]: 422,
    [ErrorType.NOT_FOUND_ERROR]: 404,
    [ErrorType.INTERNAL_SERVER_ERROR]: 500,
    [ErrorType.BAD_REQUEST_ERROR]: 400,
    [ErrorType.CONFLICT_ERROR]: 409,
    [ErrorType.INVALID_TOKEN_ERROR]: 401,
    [ErrorType.EXPIRED_TOKEN_ERROR]: 401,
    [ErrorType.UNAUTHORIZED_ERROR]: 403,
    [ErrorType.AWS_ERROR]: 502,
};
